package me.jaypatelbond.countrypicker.model

/**
 * Data class representing a country with its essential information.
 *
 * This class holds the basic information needed to display and identify a country
 * in the country picker. The flag emoji is automatically generated from the country code.
 *
 * @property name The full name of the country (e.g., "United States", "India")
 * @property code The ISO 3166-1 alpha-2 country code (e.g., "US", "IN", "GB")
 * @property dialCode The international dialing code including the plus sign (e.g., "+1", "+91", "+44")
 *
 * @sample
 * ```kotlin
 * val usa = Country(
 *     name = "United States",
 *     code = "US",
 *     dialCode = "+1"
 * )
 * println(usa.flag) // Prints: 🇺🇸
 * ```
 *
 * @see flag for the computed flag emoji property
 */
data class Country(
    val name: String,
    val code: String,
    val dialCode: String
) {
    /**
     * The flag emoji representation of this country.
     *
     * This property is computed dynamically from the [code] property using regional indicator symbols.
     * The flag is generated by converting the two-letter ISO code to Unicode regional indicator symbols.
     *
     * ## Example
     * ```kotlin
     * Country("India", "IN", "+91").flag // Returns: 🇮🇳
     * Country("Japan", "JP", "+81").flag // Returns: 🇯🇵
     * ```
     *
     * @return The flag emoji string, or an empty string if the code is invalid
     */
    val flag: String
        get() = localeToEmoji(code)
}

/**
 * Converts a two-letter ISO country code to its corresponding flag emoji.
 *
 * This function uses Unicode Regional Indicator Symbols (U+1F1E6 to U+1F1FF) to generate
 * flag emojis. Each letter of the country code is converted to its corresponding regional
 * indicator symbol.
 *
 * ## How it works
 * - Takes a 2-letter country code (e.g., "US")
 * - Converts to uppercase
 * - Maps each letter to a regional indicator symbol
 * - Combines them to form a flag emoji
 *
 * ## Examples
 * ```kotlin
 * localeToEmoji("US") // Returns: 🇺🇸
 * localeToEmoji("in") // Returns: 🇮🇳 (case-insensitive)
 * localeToEmoji("GB") // Returns: 🇬🇧
 * localeToEmoji("XYZ") // Returns: "" (invalid code)
 * ```
 *
 * @param countryCode The ISO 3166-1 alpha-2 country code (must be exactly 2 characters)
 * @return The flag emoji string, or empty string if the input is invalid
 */
fun localeToEmoji(countryCode: String): String {
    if (countryCode.length != 2) return ""
    val upper = countryCode.uppercase()
    val firstLetter = Character.codePointAt(upper, 0) - 0x41 + 0x1F1E6
    val secondLetter = Character.codePointAt(upper, 1) - 0x41 + 0x1F1E6
    return String(Character.toChars(firstLetter)) + String(Character.toChars(secondLetter))
}
